image: mcr.microsoft.com/dotnet/sdk:8.0

clone:
  depth: full

pipelines:
  branches:
    main:
      - step:
          name: Build and Push Docker Images
          services:
            - docker
          script:
            - export DOCKER_COMPOSE_VERSION=1.18.0
            - export DOCKER_COMPOSE_URL=https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-$(uname -s)-$(uname -m)
            - curl -L $DOCKER_COMPOSE_URL > docker-compose
            - chmod +x docker-compose
            - mv docker-compose /usr/local/bin
            - echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_USER" --password-stdin
            # Build both images
            - docker-compose build --force-rm --no-cache --pull
            # Tag and push frontend
            - docker tag src_frontend ${DOCKER_HUB_USER}/badmintonbooking-frontend:${BITBUCKET_BUILD_NUMBER}
            - docker push ${DOCKER_HUB_USER}/badmintonbooking-frontend:${BITBUCKET_BUILD_NUMBER}
            # Tag and push backend
            - docker tag src_backend ${DOCKER_HUB_USER}/badmintonbooking-backend:${BITBUCKET_BUILD_NUMBER}
            - docker push ${DOCKER_HUB_USER}/badmintonbooking-backend:${BITBUCKET_BUILD_NUMBER}

      - step:
          name: Mirror to GitHub
          image: atlassian/default-image:4
          script:
            - git fetch --all
            - git fetch --tags
            - git push --mirror git@github.com:orangethefish/BadmintonBooking.git
