version: 3
services:
  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - badminton-network

  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
    ports:
      - "5000:5000"
    depends_on:
      - db
    networks:
      - badminton-network

  db:
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_DATABASE=BadmintonBooking
      - MYSQL_ROOT_PASSWORD=dockerpassword
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - badminton-network

networks:
  badminton-network:
    driver: bridge

volumes:
  mysql-data:
    driver: local 